using System; using System.Collections.Generic; using System.Linq; using AshkanLMS.Models;
namespace AshkanLMS.Services { public sealed class DataService {
 public List<Student> Students {get;}=new List<Student>{new Student{Id=1001,Name="Sara Ahmadi",Email="sara@example.com",StatusKey="Active",Progress=82},new Student{Id=1002,Name="Ali Rezaei",Email="ali@example.com",StatusKey="Active",Progress=64},new Student{Id=1003,Name="Maryam Mohammadi",Email="maryam@example.com",StatusKey="Active",Progress=91},new Student{Id=1004,Name="Reza Karimi",Email="reza@example.com",StatusKey="NeedsFollowUp",Progress=38}};
 public List<Course> Courses {get;}=new List<Course>{new Course{Id=1,Title="C# & .NET Fundamentals",Instructor="Ashkan Motaei",Students=42,Progress=78,StatusKey="Active"},new Course{Id=2,Title="Clean Code in Practice",Instructor="Ashkan Motaei",Students=31,Progress=62,StatusKey="Active"},new Course{Id=3,Title="SQL Server Essentials",Instructor="N. Rahimi",Students=28,Progress=84,StatusKey="Active"},new Course{Id=4,Title="UI/UX for Desktop Apps",Instructor="S. Ahmadi",Students=25,Progress=56,StatusKey="Draft"}};
 public List<Instructor> Instructors {get;}=new List<Instructor>{new Instructor{Id=201,Name="Ashkan Motaei",Expertise="C# / .NET / Clean Code",Email="ashkan@demo.local",Courses=2},new Instructor{Id=202,Name="N. Rahimi",Expertise="SQL Server",Email="rahimi@demo.local",Courses=1},new Instructor{Id=203,Name="S. Ahmadi",Expertise="UI/UX",Email="ahmadi@demo.local",Courses=1}};
 public List<Enrollment> Enrollments {get;}=new List<Enrollment>{new Enrollment{Id=301,Student="Sara Ahmadi",Course="C# & .NET Fundamentals",Date=DateTime.Today.AddDays(-35),StatusKey="Active"},new Enrollment{Id=302,Student="Ali Rezaei",Course="Clean Code in Practice",Date=DateTime.Today.AddDays(-22),StatusKey="Active"},new Enrollment{Id=303,Student="Maryam Mohammadi",Course="SQL Server Essentials",Date=DateTime.Today.AddDays(-18),StatusKey="Completed"}};
 public List<AttendanceRecord> Attendance {get;}=new List<AttendanceRecord>{new AttendanceRecord{Id=401,Student="Sara Ahmadi",Course="C# & .NET Fundamentals",Date=DateTime.Today,StatusKey="Present"},new AttendanceRecord{Id=402,Student="Ali Rezaei",Course="Clean Code in Practice",Date=DateTime.Today,StatusKey="Absent"},new AttendanceRecord{Id=403,Student="Maryam Mohammadi",Course="SQL Server Essentials",Date=DateTime.Today,StatusKey="Present"}};
 public List<Assignment> Assignments {get;}=new List<Assignment>{new Assignment{Id=501,Title="SOLID Refactoring",Course="Clean Code in Practice",DueDate=DateTime.Today.AddDays(4),Submitted=21,StatusKey="Open"},new Assignment{Id=502,Title="LINQ Practice",Course="C# & .NET Fundamentals",DueDate=DateTime.Today.AddDays(7),Submitted=30,StatusKey="Open"}};
 public List<Exam> Exams {get;}=new List<Exam>{new Exam{Id=601,Title="C# Midterm",Course="C# & .NET Fundamentals",Date=DateTime.Today.AddDays(5),Questions=25,StatusKey="Scheduled"},new Exam{Id=602,Title="SQL Final",Course="SQL Server Essentials",Date=DateTime.Today.AddDays(10),Questions=35,StatusKey="Draft"}};
 public List<Grade> Grades {get;}=new List<Grade>{new Grade{Id=701,Student="Sara Ahmadi",Course="C# & .NET Fundamentals",Score=18.5m,Letter="A"},new Grade{Id=702,Student="Ali Rezaei",Course="Clean Code in Practice",Score=15.75m,Letter="B"},new Grade{Id=703,Student="Maryam Mohammadi",Course="SQL Server Essentials",Score=19.25m,Letter="A+"}};
 public List<Certificate> Certificates {get;}=new List<Certificate>{new Certificate{Id=801,Student="Maryam Mohammadi",Course="SQL Server Essentials",IssuedAt=DateTime.Today.AddDays(-2),Code="ALMS-SQL-0001"}};
 public List<Activity> Activities {get;}=new List<Activity>{new Activity{At=DateTime.Now.AddMinutes(-18),TypeKey="EnrollmentEvent",TextKey="EnrollmentActivity"},new Activity{At=DateTime.Now.AddHours(-2),TypeKey="ExamEvent",TextKey="ExamActivity"},new Activity{At=DateTime.Now.AddHours(-5),TypeKey="CertificateEvent",TextKey="CertificateActivity"}};
 public List<AuditEntry> Audit {get;}=new List<AuditEntry>{new AuditEntry{At=DateTime.Now.AddMinutes(-12),User="admin",ActionKey="ViewedDashboard",Entity="Dashboard"},new AuditEntry{At=DateTime.Now.AddHours(-1),User="admin",ActionKey="ChangedLanguage",Entity="Settings"}};
 int nextStudent=1100,nextCourse=20;
 public Student AddStudent(string name,string email){var s=new Student{Id=++nextStudent,Name=name,Email=email,StatusKey="Active",Progress=0};Students.Add(s);Log("Created","Student #"+s.Id);return s;}
 public Course AddCourse(string title,string instructor){var c=new Course{Id=++nextCourse,Title=title,Instructor=instructor,StatusKey="Draft",Progress=0,Students=0};Courses.Add(c);Log("Created","Course #"+c.Id);return c;}
 public void Log(string action,string entity){Audit.Insert(0,new AuditEntry{At=DateTime.Now,User="admin",ActionKey=action,Entity=entity});}
 public bool Login(string u,string p,out string role){role="";if(u.Equals("admin",StringComparison.OrdinalIgnoreCase)&&p=="1234"){role="Administrator";return true;}if(u.Equals("instructor",StringComparison.OrdinalIgnoreCase)&&p=="1234"){role="Instructor";return true;}return false;}
 }}
