using System.Collections.Generic;
using System.IO;
using System.Windows.Forms;
namespace AshkanLMS.Core {
 public static class Localization {
  static readonly Dictionary<string,string[]> D=new Dictionary<string,string[]>{
   {"LoginTitle",new[]{"ورود به AshkanLMS","Sign in to AshkanLMS"}},{"Welcome",new[]{"خوش آمدید","Welcome back"}},{"LoginSub",new[]{"برای ورود به سامانه اطلاعات حساب را وارد کنید.","Enter your account details to continue."}},{"Username",new[]{"نام کاربری","Username"}},{"Password",new[]{"رمز عبور","Password"}},{"SignIn",new[]{"ورود به سامانه","Sign in"}},{"LoginError",new[]{"نام کاربری یا رمز عبور صحیح نیست.","Incorrect username or password."}},{"BrandText",new[]{"یادگیری • مهارت • رشد\n\nسامانه مدیریت یادگیری دسکتاپ حرفه‌ای\nبا C#، .NET Framework 4.8 و WinForms","Learning • Skills • Growth\n\nA professional desktop learning management system\nbuilt with C#, .NET Framework 4.8 and WinForms."}},{"Secure",new[]{"دسترسی امن • نقش‌محور • دوزبانه","Secure access • Role based • Bilingual"}},
   {"Dashboard",new[]{"داشبورد","Dashboard"}},{"Student360",new[]{"نمای ۳۶۰ دانشجو","Student 360"}},{"Calendar",new[]{"تقویم آموزشی","Academic Calendar"}},{"NotificationCenter",new[]{"مرکز اعلان‌ها","Notification Center"}},{"OpenProfile",new[]{"نمایش پروفایل","Open profile"}},{"Students",new[]{"دانشجویان","Students"}},{"Courses",new[]{"دوره‌ها و کلاس‌ها","Courses & Classes"}},{"Instructors",new[]{"مدرسین","Instructors"}},{"Enrollments",new[]{"ثبت‌نام‌ها","Enrollments"}},{"Attendance",new[]{"حضور و غیاب","Attendance"}},{"Assignments",new[]{"تکالیف","Assignments"}},{"Exams",new[]{"آزمون و بانک سوال","Exams & Question Bank"}},{"Grades",new[]{"نمرات و کارنامه","Grades & Transcripts"}},{"Certificates",new[]{"گواهی‌ها","Certificates"}},{"Notifications",new[]{"اعلان‌ها","Notifications"}},{"Reports",new[]{"گزارش‌ها و تحلیل","Reports & Analytics"}},{"Users",new[]{"مدیریت کاربران","User Management"}},{"Audit",new[]{"گزارش ممیزی","Audit Log"}},{"Settings",new[]{"تنظیمات","Settings"}},
   {"ActiveStudents",new[]{"دانشجوی فعال","Active students"}},{"ActiveCourses",new[]{"دوره فعال","Active courses"}},{"Completion",new[]{"میانگین تکمیل","Avg. completion"}},{"PendingExams",new[]{"آزمون در انتظار","Pending exams"}},{"RunningCourses",new[]{"دوره‌های در حال اجرا","Courses in progress"}},{"RecentActivity",new[]{"فعالیت‌های اخیر","Recent activity"}},{"NewStudent",new[]{"+ دانشجوی جدید","+ New student"}},{"NewCourse",new[]{"+ دوره جدید","+ New course"}},{"StudentManagement",new[]{"مدیریت دانشجویان","Student management"}},{"CourseManagement",new[]{"دوره‌ها و کلاس‌ها","Courses & classes"}},{"Language",new[]{"English","فارسی"}},{"Today",new[]{"امروز","Today"}},
   {"Id",new[]{"شناسه","ID"}},{"Name",new[]{"نام","Name"}},{"Email",new[]{"ایمیل","Email"}},{"Progress",new[]{"پیشرفت","Progress"}},{"Status",new[]{"وضعیت","Status"}},{"Title",new[]{"عنوان","Title"}},{"Instructor",new[]{"مدرس","Instructor"}},{"StudentCount",new[]{"دانشجویان","Students"}},
   {"Active",new[]{"فعال","Active"}},{"Draft",new[]{"پیش‌نویس","Draft"}},{"NeedsFollowUp",new[]{"نیازمند پیگیری","Needs follow-up"}},{"Completed",new[]{"تکمیل شده","Completed"}},{"Present",new[]{"حاضر","Present"}},{"Absent",new[]{"غایب","Absent"}},{"Open",new[]{"باز","Open"}},{"Scheduled",new[]{"زمان‌بندی شده","Scheduled"}},
   {"Expertise",new[]{"تخصص","Expertise"}},{"CourseCount",new[]{"تعداد دوره","Courses"}},{"Student",new[]{"دانشجو","Student"}},{"Course",new[]{"دوره","Course"}},{"Date",new[]{"تاریخ","Date"}},{"DueDate",new[]{"مهلت تحویل","Due date"}},{"Submitted",new[]{"تحویل شده","Submitted"}},{"Questions",new[]{"تعداد سوال","Questions"}},{"Score",new[]{"نمره","Score"}},{"Letter",new[]{"رتبه","Grade"}},{"IssuedAt",new[]{"تاریخ صدور","Issued at"}},{"Code",new[]{"کد","Code"}},{"NewRecord",new[]{"+ رکورد جدید","+ New record"}},{"Refresh",new[]{"بازخوانی","Refresh"}},{"Delete",new[]{"حذف","Delete"}},{"Search",new[]{"جست‌وجو...","Search..."}},{"OperationalModule",new[]{"مدیریت عملیاتی","Operational management"}},
   {"EnrollmentEvent",new[]{"ثبت‌نام","Enrollment"}},{"ExamEvent",new[]{"آزمون","Exam"}},{"CertificateEvent",new[]{"گواهی","Certificate"}},{"EnrollmentActivity",new[]{"دانشجوی جدید به دوره C# & .NET اضافه شد.","A new student joined C# & .NET."}},{"ExamActivity",new[]{"آزمون Clean Code منتشر شد.","The Clean Code exam was published."}},{"CertificateActivity",new[]{"۳ گواهی پایان دوره صادر شد.","3 course certificates were issued."}},
   {"Created",new[]{"ایجاد شد","Created"}},{"ViewedDashboard",new[]{"مشاهده داشبورد","Viewed dashboard"}},{"ChangedLanguage",new[]{"تغییر زبان","Changed language"}},{"User",new[]{"کاربر","User"}},{"Action",new[]{"عملیات","Action"}},{"Entity",new[]{"موجودیت","Entity"}},{"Time",new[]{"زمان","Time"}},
   {"GlobalSearch",new[]{"جست‌وجوی سراسری","Global Search"}},{"SearchHint",new[]{"نام دانشجو، دوره یا مدرس را جست‌وجو کنید...","Search students, courses or instructors..."}},{"RiskCenter",new[]{"مرکز ریسک و پیشرفت","Risk & Progress Center"}},{"AtRisk",new[]{"نیازمند توجه","At risk"}},{"Healthy",new[]{"وضعیت مناسب","Healthy"}},{"ReportCenter",new[]{"مرکز گزارش‌ها","Report Center"}},{"ExportCsv",new[]{"خروجی CSV","Export CSV"}},{"Course360",new[]{"نمای ۳۶۰ دوره","Course 360"}},{"InstructorWorkspace",new[]{"فضای کاری مدرس","Instructor Workspace"}},{"QuickInsights",new[]{"بینش‌های سریع","Quick insights"}},{"AverageScore",new[]{"میانگین نمره","Average score"}},{"UpcomingExams",new[]{"آزمون‌های پیش رو","Upcoming exams"}},{"CompletionRate",new[]{"نرخ تکمیل","Completion rate"}},{"SecurityCenter",new[]{"مرکز امنیت و دسترسی","Security & Access Center"}},{"RoleAware",new[]{"ناوبری و قابلیت‌های متناسب با نقش کاربر","Role-aware navigation and capabilities"}},
   {"AdvancedSearch",new[]{"جست‌وجو و فیلتر پیشرفته","Advanced search and filtering"}},{"Export",new[]{"خروجی CSV و چاپ گزارش","CSV export and report printing"}},{"RBAC",new[]{"کنترل دسترسی مبتنی بر نقش","Role-based access control"}},{"Validation",new[]{"اعتبارسنجی و وضعیت خطای استاندارد","Standard validation and error states"}},{"AuditReady",new[]{"ثبت رویدادهای قابل ممیزی","Audit-ready actions"}},{"Responsive",new[]{"چیدمان سازگار با تغییر اندازه پنجره","Resize-aware desktop layout"}},{"ModuleDesc",new[]{"این ماژول در معماری AshkanLMS برای عملیات کامل، گردش‌کار، گزارش‌گیری و کنترل دسترسی آماده شده است.","This AshkanLMS module is prepared for full operations, workflows, reporting and access control."}}
  };
  public static string T(string key){string[] v; return D.TryGetValue(key,out v)?v[AppSession.Persian?0:1]:key;}
  public static void Load(){try{var p=Path.Combine(Application.UserAppDataPath,"language.txt"); if(File.Exists(p)) AppSession.Persian=File.ReadAllText(p).Trim()!="en";}catch{}}
  public static void Set(bool persian){AppSession.Persian=persian; try{Directory.CreateDirectory(Application.UserAppDataPath);File.WriteAllText(Path.Combine(Application.UserAppDataPath,"language.txt"),persian?"fa":"en");}catch{}}
  public static void Direction(Form f){LayoutDirectionManager.Apply(f);}
 }
}
