using System.Drawing;
using System.Drawing.Drawing2D;
using System.Windows.Forms;
namespace AshkanLMS.Core {
 public class GradientPanel:Panel { public Color StartColor{get;set;}=Color.FromArgb(235,242,252); public Color EndColor{get;set;}=Color.FromArgb(220,232,247); public float Angle{get;set;}=35f; protected override void OnPaintBackground(PaintEventArgs e){using(var b=new LinearGradientBrush(ClientRectangle,StartColor,EndColor,Angle))e.Graphics.FillRectangle(b,ClientRectangle);} }

 public class BackgroundPanel:Panel { string imagePath; public string ImagePath{get{return imagePath;}set{if(imagePath==value)return;imagePath=value;if(image!=null){image.Dispose();image=null;}Invalidate();}} public Color OverlayColor{get;set;}=Color.FromArgb(110,12,25,48); Image image; public BackgroundPanel(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);} protected override void OnPaintBackground(PaintEventArgs e){base.OnPaintBackground(e); if(image==null&&!string.IsNullOrEmpty(ImagePath)){try{if(System.IO.File.Exists(ImagePath))image=Image.FromFile(ImagePath);}catch{}} if(image!=null){float sx=(float)Width/image.Width,sy=(float)Height/image.Height,scale=System.Math.Max(sx,sy);int w=(int)(image.Width*scale),h=(int)(image.Height*scale);int x=(Width-w)/2,y=(Height-h)/2;e.Graphics.DrawImage(image,new Rectangle(x,y,w,h));} using(var b=new SolidBrush(OverlayColor))e.Graphics.FillRectangle(b,ClientRectangle);} protected override void Dispose(bool disposing){if(disposing&&image!=null){image.Dispose();image=null;}base.Dispose(disposing);} }
 public class ModernCard:Panel { public ModernCard(){BackColor=Color.FromArgb(248,250,254);Padding=new Padding(18);SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);} protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);using(var p=new Pen(Color.FromArgb(218,226,238)))e.Graphics.DrawRectangle(p,0,0,Width-1,Height-1);} }
}
